### ISSUE TITLE
我的总是 取消关联成功，无法关联

### ISSUE THREAD

**Issue by AlbertWang2018** [leoxiaofei/IFEONpp#1]
![Npp关联失败](https://github.com/leoxiaofei/IFEONpp/assets/36392874/a3fa51d4-f492-4fd3-a509-3a89486fd98d)
win11 23H2，我知道修改注册表可以实现这个功能，但仍然期待作者修复这个bug。

**Comment by leoxiaofei** [comment]
好久没用notepad++了，有时间我试试。

**Comment by leoxiaofei** [comment]
@AlbertWang2018 改了一下，发布了，有时间测试一下。

**Comment by AlbertWang2018** [comment]
> @AlbertWang2018 改了一下，发布了，有时间测试一下。

试了一下，可以了，非常感谢。
